server:
  port: 8081

spring:
  application:
    name: dailyrent-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rentalapp
      username: root
      password: root
      authentication-database: admin

