server:
  port: 8080

spring:
  application:
    name: inventory
  datasource:
    username: 'root'
    url: jdbc:postgresql://localhost:5432/inventory
    password: 'root'

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://192.168.50.10:8761/eureka/
    fetch-registry: true
    register-with-eureka: true